name: Bug Report
description: File a bug report.
title: "[Bug]: "
type: "Bug"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: example@liva-pms.com
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Clearly and specifically identify the issue, stick to one bug per bug report and make sure the bug keeps occurring. Keep the bug report brief, stick to the facts, and include only relevant details
      placeholder:
      value:      |

        **Description:**



        **Steps to Reproduce:**

        1. 
        2.
        3.

        **Expected vs. Actual Results:**

        Expected:
        Actual:

        **Analysis Results:**

        Criticality: 0 = Critical

          - Class: 0
          - Severity: 0
          - Likelihood: 0

        CVSS v4.0 Score: 0 / None
        CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N

    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
